# Generated by Django 2.1.7 on 2019-04-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKS',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('AUTHOR', models.CharField(max_length=50)),
                ('PUBLISHING_HOUSE', models.CharField(max_length=50)),
                ('NUM', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BORROR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEADLINE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='READER',
            fields=[
                ('ACCOUNT', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PASSWORD', models.CharField(max_length=300)),
                ('NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='REVIEW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCORE', models.IntegerField()),
                ('COMMENT', models.CharField(max_length=300)),
                ('ACCOUNT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.READER')),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.BOOKS')),
            ],
        ),
        migrations.AddField(
            model_name='borror',
            name='ACCOUNT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.READER'),
        ),
        migrations.AddField(
            model_name='borror',
            name='ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.BOOKS'),
        ),
    ]
